### ISSUE TITLE
comprehension of _get_metadata_from_file

### ISSUE THREAD

**Issue by as142** [Proteus-tech/nikola#1]
Hi there, When I was learning and trying to understand the function "_get_metadata_from_file" in nikola/nikola/post.py, I was confused about the description of its delivered function. My understanding of this code snippet is "extract metadata from a source file". Do I understand that right?

**Comment by KayEss** [comment]
This is a fork of the project. I think this is the actual project repository: <https://github.com/getnikola/nikola>. You're more likely to get a proper answer there.
